services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4652:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      sistema-de-aposta:
  
  frontend:
    container_name: frontend
    build: 
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on: ["backend"]
    networks:
      sistema-de-aposta:
    volumes:
      - ./backend:/backend
    


networks:
  sistema-de-aposta:
    driver: bridge