// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("backend.Models.Apostas.Aposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerosEscolhidos")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SorteioGanhadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SorteioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SorteioGanhadorId");

                    b.HasIndex("SorteioId");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("backend.Models.Sorteios.GanhadorSorteio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfGanhador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAposta")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAposta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSorteio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeGanhador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerosEscolhidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ganhadores");
                });

            modelBuilder.Entity("backend.Models.Sorteios.Sorteio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerosGanhadores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sorteios");
                });

            modelBuilder.Entity("backend.Models.Apostas.Aposta", b =>
                {
                    b.HasOne("backend.Models.Sorteios.Sorteio", "SorteioGanhador")
                        .WithMany()
                        .HasForeignKey("SorteioGanhadorId");

                    b.HasOne("backend.Models.Sorteios.Sorteio", "Sorteio")
                        .WithMany("TodasApostas")
                        .HasForeignKey("SorteioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sorteio");

                    b.Navigation("SorteioGanhador");
                });

            modelBuilder.Entity("backend.Models.Sorteios.Sorteio", b =>
                {
                    b.Navigation("TodasApostas");
                });
#pragma warning restore 612, 618
        }
    }
}
